#!/usr/bin/env python

from deb import *

rebuild_work_directory()
setup_plt_directory('master')

for distro in distros:
    print "Create package for distro '%s'" % distro
    create_nightly(distro)
